export function controlPanelHtml(nonce: string) {
  return String.raw`<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>rareteam control</title>
  <style>
    :root{color-scheme:dark;--bg:#070a0f;--panel:#101722;--panel2:#151f2c;--line:#263548;--text:#f4f7fb;--muted:#8290a3;--cyan:#35d5ff;--red:#ff5267;--green:#43e19b}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#102338 0,transparent 36%),var(--bg);color:var(--text);font:14px Inter,Arial,sans-serif;min-height:100vh}
    button,input,select,textarea{font:inherit}.hidden{display:none!important}.shell{display:grid;grid-template-columns:230px 1fr;min-height:100vh}
    aside{border-right:1px solid var(--line);padding:28px 18px;background:#090e15d9;backdrop-filter:blur(18px);position:sticky;top:0;height:100vh}
    .brand{font-size:25px;font-weight:900;letter-spacing:1px;margin:0 12px 34px}.brand i{color:var(--cyan);font-style:normal}.brand small{display:block;color:var(--muted);font-size:9px;letter-spacing:3px;margin-top:4px}
    nav button{display:flex;width:100%;border:0;background:transparent;color:var(--muted);padding:12px 14px;border-radius:10px;margin:4px 0;cursor:pointer;text-align:left}nav button:hover,nav button.active{color:#fff;background:#152231}
    main{padding:34px;max-width:1480px;width:100%;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:26px}.top h1{margin:0;font-size:28px}.top p{color:var(--muted);margin:6px 0 0}
    .chip,.btn{border:1px solid var(--line);background:var(--panel2);color:#fff;border-radius:9px;padding:9px 13px}.btn{cursor:pointer}.btn.primary{background:var(--cyan);border-color:var(--cyan);color:#041019;font-weight:800}.btn.danger{color:#fff;background:#53202a;border-color:#853442}.btn:disabled{opacity:.5}
    .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px}.card{background:linear-gradient(145deg,#131c28,#0d141e);border:1px solid var(--line);border-radius:15px;padding:18px;box-shadow:0 12px 40px #0004}.metric span{color:var(--muted);text-transform:uppercase;font-size:10px;letter-spacing:1px}.metric b{display:block;font-size:30px;margin-top:9px}.server-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.server-card{display:flex;justify-content:space-between;align-items:center}.server-card b,.server-card span{display:block}.server-card small{color:var(--muted)}.server-card .online{color:var(--green)}.server-card .offline{color:var(--red)}
    .panel{margin-top:18px}.toolbar{display:flex;gap:10px;align-items:center;margin-bottom:14px}.toolbar input,.toolbar select,.field input,.field select,.field textarea{background:#09101a;border:1px solid var(--line);border-radius:8px;color:#fff;padding:10px;width:100%}
    table{width:100%;border-collapse:collapse}th{text-align:left;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:1px;padding:10px}td{padding:12px 10px;border-top:1px solid #1c2938;vertical-align:middle}.role{display:inline-flex;align-items:center;gap:6px;border:1px solid currentColor;border-radius:20px;padding:4px 8px;margin:2px;font-size:11px}.role img{width:15px;height:15px;object-fit:contain}.muted{color:var(--muted)}.ban{color:#ff8996}
    .role-list{display:grid;gap:9px}.role-row{display:grid;grid-template-columns:36px 1fr auto auto;align-items:center;gap:12px;background:#0c131d;border:1px solid var(--line);border-radius:12px;padding:11px}.role-icon{width:34px;height:34px;border-radius:9px;background:#182433;display:grid;place-items:center;overflow:hidden}.role-icon img{width:100%;height:100%;object-fit:cover}
    .announcement-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.announcement-card{overflow:hidden;padding:0}.announcement-image{height:150px;background:linear-gradient(135deg,#132333,#09111a);display:grid;place-items:center;color:var(--muted)}.announcement-image img{width:100%;height:100%;object-fit:cover}.announcement-copy{padding:16px}.announcement-copy h3{margin:0 0 8px}.announcement-copy p{color:var(--muted);line-height:1.5;white-space:pre-wrap}.announcement-meta{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:14px}.published{color:var(--green)}.draft{color:var(--muted)}
    .modal{position:fixed;inset:0;background:#000a;display:grid;place-items:center;padding:24px;z-index:20}.dialog{width:min(720px,100%);max-height:90vh;overflow:auto;background:#101823;border:1px solid #33475f;border-radius:16px;padding:22px}.dialog h2{margin-top:0}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field label{display:block;color:var(--muted);font-size:11px;margin-bottom:6px}.permissions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:14px 0}.perm{display:flex;gap:8px;align-items:center;background:#0a111a;padding:8px;border-radius:7px}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:16px}
    .login{min-height:100vh;display:grid;place-items:center}.login form{width:min(390px,90vw)}.login .brand{text-align:center;margin:0 0 24px}.login input{display:block;width:100%;margin:10px 0;background:#09101a;border:1px solid var(--line);color:#fff;border-radius:9px;padding:12px}.error{color:#ff7384}.toast{position:fixed;right:25px;bottom:25px;padding:12px 16px;background:#172536;border:1px solid #34506b;border-radius:9px;z-index:30}
    @media(max-width:900px){.shell{grid-template-columns:1fr}aside{position:static;height:auto}.grid{grid-template-columns:repeat(2,1fr)}.fields,.permissions{grid-template-columns:1fr}main{padding:20px}}
  </style>
</head>
<body>
<section id="login" class="login"><form id="loginForm" class="card"><div class="brand">rare<i>team</i><small>CONTROL SYSTEM</small></div><input name="login" placeholder="Ник или email" required><input name="password" type="password" placeholder="Пароль" required><p id="loginError" class="error"></p><button class="btn primary" style="width:100%">ВОЙТИ</button></form></section>
<section id="app" class="shell hidden">
  <aside><div class="brand">rare<i>team</i><small>CONTROL SYSTEM</small></div><nav>
    <button data-page="overview" class="active">Обзор</button><button data-page="users">Пользователи</button><button data-page="roles">Роли</button><button id="announcementsNav" data-page="announcements">Новости</button><button data-page="audit">Аудит</button>
  </nav></aside>
  <main><header class="top"><div><h1 id="title">Обзор</h1><p id="subtitle">Центральное управление rareteam</p></div><div><span id="actor" class="chip"></span> <button id="logout" class="btn">Выйти</button></div></header>
    <section id="overviewPage"><div id="metrics" class="grid"></div><div class="card panel"><h3>Игровые серверы</h3><div id="serverMetrics" class="server-grid"></div></div><div class="card panel"><h3>Единая система доступа</h3><p class="muted">Роли и блокировки глобальны. Minecraft подключён через rare-auth; адаптер CSS v34 подготовлен для следующего этапа авторизации.</p></div></section>
    <section id="usersPage" class="hidden"><div class="toolbar"><input id="userSearch" placeholder="Поиск по нику, email или UUID"><button id="searchUsers" class="btn">Найти</button></div><div class="card"><table><thead><tr><th>Пользователь</th><th>Роли</th><th>Состояние</th><th></th></tr></thead><tbody id="usersBody"></tbody></table></div></section>
    <section id="rolesPage" class="hidden"><div class="toolbar"><button id="newRole" class="btn primary">Создать роль</button></div><div id="rolesList" class="role-list"></div></section>
    <section id="announcementsPage" class="hidden"><div class="toolbar"><button id="newAnnouncement" class="btn primary">Создать новость</button></div><div id="announcementsList" class="announcement-list"></div></section>
    <section id="auditPage" class="hidden"><div class="card"><table><thead><tr><th>Время</th><th>Сотрудник</th><th>Действие</th><th>Объект</th></tr></thead><tbody id="auditBody"></tbody></table></div></section>
  </main>
</section>
<div id="modal" class="modal hidden"><div id="dialog" class="dialog"></div></div><div id="toast" class="toast hidden"></div>
<script nonce="${nonce}">
const state={session:null,roles:[],permissions:[],users:[],announcements:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){const e=$('#toast');e.textContent=text;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2500)}
async function raw(path,options={}){const r=await fetch(path,{...options,credentials:'same-origin'});if(!r.ok){let j={};try{j=await r.json()}catch{}throw new Error(j.error||'HTTP '+r.status)}return r}
async function api(path,options={}){const r=await raw(path,options);if(r.status===204)return null;return r.json()}
async function boot(){try{state.session=await api('/control/api/session');$('#actor').textContent=state.session.user.username;const canNews=state.session.permissions.includes('*')||state.session.permissions.includes('content.announcements');$('#announcementsNav').classList.toggle('hidden',!canNews);$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await show('overview')}catch(x){state.session=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const data=Object.fromEntries(new FormData(e.currentTarget));try{await api('/control/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});await boot()}catch(x){$('#loginError').textContent=x.message}});
$('#logout').onclick=async()=>{await raw('/control/api/logout',{method:'POST'});location.reload()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
async function show(page){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));['overview','users','roles','announcements','audit'].forEach(x=>$('#'+x+'Page').classList.toggle('hidden',x!==page));$('#title').textContent={overview:'Обзор',users:'Пользователи',roles:'Роли',announcements:'Новости',audit:'Аудит'}[page];if(page==='overview')await loadOverview();if(page==='users')await loadUsers();if(page==='roles')await loadRoles();if(page==='announcements')await loadAnnouncements();if(page==='audit')await loadAudit()}
async function loadOverview(){const x=await api('/control/api/overview');const uptime=Math.floor(x.uptimeSeconds/3600)+' ч';$('#metrics').innerHTML=[['Пользователи',x.users],['Новые за 24 часа',x.new_users_24h],['Активные баны',x.active_bans],['Роли',x.roles],['Активные сессии',x.active_sessions],['Uptime API',uptime],['Память API',x.memoryMb+' МБ']].map(v=>'<div class="card metric"><span>'+v[0]+'</span><b>'+v[1]+'</b></div>').join('');$('#serverMetrics').innerHTML=(x.servers||[]).map(v=>'<div class="card server-card"><div><b>'+esc(v.name)+'</b><small>'+esc(v.map||v.id)+'</small></div><div><span class="'+(v.online?'online':'offline')+'">● '+(v.online?'ONLINE':'OFFLINE')+'</span><small>'+v.players+' / '+v.maxPlayers+'</small></div></div>').join('')}
async function ensureRoles(){state.roles=await api('/control/api/roles');return state.roles}
function roleHtml(r){return '<span class="role" style="color:'+esc(r.color)+'">'+(r.iconUrl?'<img src="'+esc(r.iconUrl)+'">':'◆')+esc(r.name)+'</span>'}
async function loadUsers(){await ensureRoles();const q=$('#userSearch').value;state.users=await api('/control/api/users?q='+encodeURIComponent(q));$('#usersBody').innerHTML=state.users.map(u=>'<tr><td><b>'+esc(u.username)+'</b><br><span class="muted">'+esc(u.email)+' · '+esc(u.minecraft_uuid)+'</span></td><td>'+(u.role_assignments||[]).map(r=>roleHtml({name:r.name,color:r.color,iconUrl:r.iconKey?'/artifacts/'+r.iconKey:null})).join('')+'</td><td>'+(u.active_ban?'<b class="ban">Заблокирован</b><br><span class="muted">'+esc(u.active_ban.reason)+'</span>':'<span style="color:var(--green)">Активен</span>')+'</td><td><button class="btn" data-action="manage-user" data-id="'+esc(u.id)+'">Управлять</button></td></tr>').join('')}
$('#searchUsers').onclick=loadUsers;$('#userSearch').onkeydown=e=>{if(e.key==='Enter')loadUsers()};
async function manageUser(id){const u=state.users.find(x=>x.id===id);if(!u)return;const name=u.username;const roleOptions=state.roles.filter(r=>!r.isSystem).map(r=>'<option value="'+r.id+'">'+esc(r.name)+'</option>').join('');openModal('<h2>'+esc(name)+'</h2><h3>Выдать роль</h3><div class="fields"><div class="field"><label>Роль</label><select id="assignRole">'+roleOptions+'</select></div><div class="field"><label>Сервер (пусто = глобально)</label><input id="assignServer" placeholder="melchior-1"></div><div class="field"><label>Истекает</label><input id="assignExpires" type="datetime-local"></div><div class="field"><label>Причина</label><input id="assignReason"></div></div><button class="btn primary" id="assignDo">Выдать</button><h3>Блокировка</h3><div class="fields"><div class="field"><label>Область</label><select id="banScope"><option value="global">Все серверы</option><option value="server">Один сервер</option></select></div><div class="field"><label>Сервер</label><input id="banServer" placeholder="melchior-1"></div><div class="field"><label>Причина</label><input id="banReason"></div><div class="field"><label>Истекает</label><input id="banExpires" type="datetime-local"></div></div><div class="actions"><button class="btn" data-action="close-modal">Закрыть</button><button class="btn danger" id="banDo">Заблокировать</button></div>');$('#assignDo').onclick=async()=>{await api('/control/api/users/'+id+'/roles',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({roleId:$('#assignRole').value,serverId:$('#assignServer').value||null,expiresAt:$('#assignExpires').value?new Date($('#assignExpires').value).toISOString():null,reason:$('#assignReason').value})});toast('Роль выдана');closeModal();loadUsers()};$('#banDo').onclick=async()=>{await api('/control/api/users/'+id+'/bans',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scope:$('#banScope').value,serverId:$('#banServer').value||null,reason:$('#banReason').value,expiresAt:$('#banExpires').value?new Date($('#banExpires').value).toISOString():null})});toast('Пользователь заблокирован');closeModal();loadUsers()}}
async function loadRoles(){state.permissions=(await api('/control/api/permissions')).permissions;await ensureRoles();$('#rolesList').innerHTML=state.roles.map(r=>'<div class="role-row"><div class="role-icon">'+(r.iconUrl?'<img src="'+esc(r.iconUrl)+'">':'◆')+'</div><div><b style="color:'+esc(r.color)+'">'+esc(r.name)+'</b><br><span class="muted">'+r.memberCount+' участников · позиция '+r.position+'</span></div><span>'+r.permissions.length+' прав</span>'+(r.isSystem?'<span class="chip">Системная</span>':'<button class="btn" data-action="edit-role" data-id="'+esc(r.id)+'">Изменить</button>')+'</div>').join('')}
$('#newRole').onclick=()=>editRole(null);
function editRole(id){const r=state.roles.find(x=>x.id===id)||{name:'',color:'#35d5ff',position:0,permissions:[],scopes:['global'],displayInTab:true};const checks=state.permissions.map(p=>'<label class="perm"><input type="checkbox" value="'+p+'" '+(r.permissions.includes(p)?'checked':'')+'>'+p+'</label>').join('');openModal('<h2>'+(id?'Изменить роль':'Новая роль')+'</h2><div class="fields"><div class="field"><label>Название</label><input id="roleName" value="'+esc(r.name)+'"></div><div class="field"><label>Цвет</label><input id="roleColor" type="color" value="'+esc(r.color)+'"></div><div class="field"><label>Позиция</label><input id="rolePosition" type="number" value="'+r.position+'"></div><div class="field"><label>Области через запятую</label><input id="roleScopes" value="'+esc(r.scopes.join(','))+'"></div></div><h3>Возможности</h3><div class="permissions">'+checks+'</div><label class="perm"><input id="roleTab" type="checkbox" '+(r.displayInTab?'checked':'')+'>Показывать роль в TAB</label>'+(id?'<div class="field"><label>Значок PNG</label><input id="roleIcon" type="file" accept=".png,image/png"></div>':'')+'<div class="actions"><button class="btn" data-action="close-modal">Отмена</button>'+(id?'<button id="deleteRole" class="btn danger">Удалить</button>':'')+'<button id="saveRole" class="btn primary">Сохранить</button></div>');$('#saveRole').onclick=async()=>{const body={name:$('#roleName').value,color:$('#roleColor').value,position:Number($('#rolePosition').value),permissions:[...document.querySelectorAll('.permissions input:checked')].map(x=>x.value),scopes:$('#roleScopes').value.split(',').map(x=>x.trim()).filter(Boolean),displayInTab:$('#roleTab').checked};let roleId=id;if(id)await api('/control/api/roles/'+id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});else{const created=await api('/control/api/roles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});roleId=created.id}const file=$('#roleIcon')?.files?.[0];if(file&&roleId){const form=new FormData();form.append('file',file);await api('/control/api/roles/'+roleId+'/icon',{method:'POST',body:form})}toast('Роль сохранена');closeModal();loadRoles()};if(id)$('#deleteRole').onclick=async()=>{if(confirm('Удалить роль?')){await api('/control/api/roles/'+id,{method:'DELETE'});closeModal();loadRoles()}}}
async function loadAnnouncements(){state.announcements=await api('/control/api/announcements');$('#announcementsList').innerHTML=state.announcements.length?state.announcements.map(x=>'<article class="card announcement-card"><div class="announcement-image">'+(x.imageUrl?'<img src="'+esc(x.imageUrl)+'" alt="">':'НЕТ ИЗОБРАЖЕНИЯ')+'</div><div class="announcement-copy"><h3>'+esc(x.title)+'</h3><p>'+esc(x.summary)+'</p><div class="announcement-meta"><span class="'+(x.published?'published':'draft')+'">'+(x.published?'Опубликована':'Черновик')+'</span><button class="btn" data-action="edit-announcement" data-id="'+esc(x.id)+'">Изменить</button></div></div></article>').join(''):'<div class="card muted">Новостей пока нет. Создайте первую публикацию для главной страницы лаунчера.</div>'}
$('#newAnnouncement').onclick=()=>editAnnouncement(null);
function editAnnouncement(id){const x=state.announcements.find(v=>v.id===id)||{title:'',summary:'',published:false};openModal('<h2>'+(id?'Изменить новость':'Новая новость')+'</h2><div class="field"><label>Заголовок</label><input id="announcementTitle" maxlength="120" value="'+esc(x.title)+'"></div><div class="field"><label>Текст</label><textarea id="announcementSummary" rows="7" maxlength="4000">'+esc(x.summary)+'</textarea></div><label class="perm"><input id="announcementPublished" type="checkbox" '+(x.published?'checked':'')+'>Опубликовать в лаунчере</label><div class="field"><label>Изображение (PNG, JPEG или WebP, до 2 МБ)</label><input id="announcementImage" type="file" accept="image/png,image/jpeg,image/webp"></div><div class="actions"><button class="btn" data-action="close-modal">Отмена</button>'+(id?'<button id="deleteAnnouncement" class="btn danger">Удалить</button>':'')+'<button id="saveAnnouncement" class="btn primary">Сохранить</button></div>');$('#saveAnnouncement').onclick=async()=>{const body={title:$('#announcementTitle').value,summary:$('#announcementSummary').value,published:$('#announcementPublished').checked};let announcementId=id;if(id)await api('/control/api/announcements/'+id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});else{const created=await api('/control/api/announcements',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});announcementId=created.id}const file=$('#announcementImage').files?.[0];if(file&&announcementId){const form=new FormData();form.append('image',file);await api('/control/api/announcements/'+announcementId+'/image',{method:'POST',body:form})}toast('Новость сохранена');closeModal();loadAnnouncements()};if(id)$('#deleteAnnouncement').onclick=async()=>{if(confirm('Удалить новость?')){await api('/control/api/announcements/'+id,{method:'DELETE'});closeModal();loadAnnouncements()}}}
async function loadAudit(){const rows=await api('/control/api/audit');$('#auditBody').innerHTML=rows.map(x=>'<tr><td>'+new Date(x.created_at).toLocaleString()+'</td><td>'+esc(x.actor||'system')+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.target||'—')+'</td></tr>').join('')}
function openModal(html){$('#dialog').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='close-modal')closeModal();if(b.dataset.action==='manage-user')void manageUser(b.dataset.id);if(b.dataset.action==='edit-role')editRole(b.dataset.id);if(b.dataset.action==='edit-announcement')editAnnouncement(b.dataset.id)});
boot();
</script></body></html>`;
}